openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/geoCache:
    post:
      tags:
      - geo-cache
      operationId: receiveSubmission
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeoCacheSubmission"
        required: true
      responses:
        "200":
          description: OK
components:
  schemas:
    GeoCacheSubmission:
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 3
          pattern: "/[ -~]/"
          type: string
        note:
          maxLength: 250
          minLength: 3
          pattern: "/[ -~]/"
          type: string
        secret:
          maxLength: 50
          minLength: 3
          pattern: "/[ -~]/"
          type: string
