openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /api/v1/geoCache:
    post:
      operationId: receiveSubmission
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeoCacheSubmission'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - geo-cache
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    GeoCacheSubmission:
      example:
        note: note
        name: name
        secret: secret
      properties:
        name:
          maxLength: 50
          minLength: 3
          pattern: "/[ -~]/"
          type: string
        note:
          maxLength: 250
          minLength: 3
          pattern: "/[ -~]/"
          type: string
        secret:
          maxLength: 50
          minLength: 3
          pattern: "/[ -~]/"
          type: string
      type: object

