name: Run Spring Boot Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: 'maven'

      - name: Build and Run Tests
        run: mvn clean test
